import type { HomeGymPost } from "@/lib/types";

export const gymPosts: HomeGymPost[] = [
  {
    id: "01",
    slug: "garage-power-rack",
    title: "ガレージに作った本格パワーラック部屋",
    owner: "Ken / Strength Log",
    location: "神奈川県",
    scale: "serious",
    areaSqm: 12,
    budget: 860000,
    monthlyMaintenance: 2500,
    tags: ["パワーラック", "バーベル", "防音", "ガレージ"],
    summary: "車1台分のガレージを半分使い、床補強とラバーマットを厚めにした高重量向けの構成。",
    highlights: ["床は50mm合板と20mmラバー", "夜間用にLEDバーを追加", "壁面収納でプレートを整理"],
    images: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=1200&auto=format&fit=crop",
    ],
    gear: [
      { name: "パワーラック PRO", maker: "Iron Base", price: 248000, url: "https://example.com/rack", category: "ラック" },
      { name: "オリンピックバーベル 20kg", maker: "Forge", price: 42000, url: "https://example.com/barbell", category: "バーベル" },
      { name: "ラバープレート 140kg", maker: "Plate Works", price: 178000, url: "https://example.com/plates", category: "プレート" },
    ],
    sns: { instagram: "https://instagram.com", youtube: "https://youtube.com" },
    likes: 428,
    saved: 172,
  },
  {
    id: "02",
    slug: "one-room-yoga-strength",
    title: "ワンルームのヨガマット + チューブ構成",
    owner: "Mika Fit",
    location: "東京都",
    scale: "compact",
    areaSqm: 2.5,
    budget: 26000,
    monthlyMaintenance: 0,
    tags: ["省スペース", "ヨガ", "チューブ", "賃貸OK"],
    summary: "家具の配置を変えず、朝だけ広げられるミニマルなホームジム。収納はベッド下に集約。",
    highlights: ["全アイテムを1分で片付け", "床傷対策で厚手マット", "宅トレ動画用のスマホ三脚あり"],
    images: [
      "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1591291621164-2c6367723315?q=80&w=1200&auto=format&fit=crop",
    ],
    gear: [
      { name: "折りたたみヨガマット 8mm", maker: "Mat & Co", price: 6800, url: "https://example.com/yoga-mat", category: "マット" },
      { name: "トレーニングチューブ 5本セット", maker: "Flex", price: 3600, url: "https://example.com/bands", category: "チューブ" },
      { name: "可変式ダンベル 2kg", maker: "HomeFit", price: 5200, url: "https://example.com/dumbbell", category: "ダンベル" },
    ],
    sns: { instagram: "https://instagram.com", x: "https://x.com" },
    likes: 231,
    saved: 118,
  },
  {
    id: "03",
    slug: "family-living-room-gym",
    title: "家族で使うリビング横の可変式ダンベル空間",
    owner: "Takumi Home Training",
    location: "大阪府",
    scale: "standard",
    areaSqm: 5,
    budget: 185000,
    monthlyMaintenance: 800,
    tags: ["可変式ダンベル", "家族共有", "収納", "マンション"],
    summary: "テレビ横の一角を活用し、可変式ダンベルと折りたたみベンチで筋トレとストレッチを両立。",
    highlights: ["ベンチは縦置き収納", "子ども用ロック付きラック", "生活感が出ない黒系で統一"],
    images: [
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1200&auto=format&fit=crop",
    ],
    gear: [
      { name: "可変式ダンベル 24kg ペア", maker: "QuickBell", price: 78000, url: "https://example.com/adjustable", category: "ダンベル" },
      { name: "折りたたみインクラインベンチ", maker: "Bench Lab", price: 36000, url: "https://example.com/bench", category: "ベンチ" },
      { name: "防振マット 6枚", maker: "Quiet Floor", price: 14800, url: "https://example.com/mat", category: "床材" },
    ],
    sns: { youtube: "https://youtube.com" },
    likes: 312,
    saved: 146,
  },
  {
    id: "04",
    slug: "tiny-balcony-cardio",
    title: "ベランダ前に置いた静音バイク中心の有酸素セット",
    owner: "Nao Cycle Room",
    location: "福岡県",
    scale: "compact",
    areaSqm: 3.2,
    budget: 72000,
    monthlyMaintenance: 500,
    tags: ["有酸素", "静音", "バイク", "在宅勤務"],
    summary: "仕事前後に短時間で使えるよう、静音バイクとフォームローラーを窓際にまとめた構成。",
    highlights: ["汗対策で洗えるラグ", "タブレット台を追加", "心拍計と連携して記録"],
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?q=80&w=1200&auto=format&fit=crop",
    ],
    gear: [
      { name: "静音スピンバイク", maker: "RideHome", price: 54800, url: "https://example.com/bike", category: "有酸素" },
      { name: "フォームローラー", maker: "Recovery", price: 2800, url: "https://example.com/roller", category: "ケア" },
      { name: "心拍センサー", maker: "Pulse", price: 9800, url: "https://example.com/hr", category: "計測" },
    ],
    sns: { instagram: "https://instagram.com" },
    likes: 184,
    saved: 74,
  },
];

export const scaleLabels = {
  compact: "コンパクト",
  standard: "標準",
  serious: "本格派",
} as const;
