import type { ProductCategory, RankingProduct } from "@/lib/types";

export const productCategoryLabels: Record<ProductCategory, string> = {
  "multi-home-gym": "マルチホームジム",
  "power-rack": "パワーラック・スミス",
  "pull-up-stand": "懸垂マシン",
  "adjustable-dumbbell": "可変式ダンベル",
  bench: "トレーニングベンチ",
  "floor-mat": "床材・防振マット",
  mirror: "鏡",
  cardio: "有酸素マシン",
  "compact-gym": "省スペース器具",
  accessory: "小物・収納",
};

export const productCategoryDescriptions: Record<ProductCategory, string> = {
  "multi-home-gym": "ラットプル、チェストプレス、アブ系まで1台でまとめたい人向け。",
  "power-rack": "ベンチプレス、スクワット、懸垂を本格的に伸ばしたい人向け。",
  "pull-up-stand": "低予算で背中・腕・体幹を鍛えたい人の定番アイテム。",
  "adjustable-dumbbell": "省スペースで全身を鍛えたい人の最初の主役アイテム。",
  bench: "ダンベル種目や腹筋種目の幅を広げるホームジムの土台。",
  "floor-mat": "床傷、防音、防振を抑えるための必須インフラ。",
  mirror: "フォーム確認や空間を広く見せるための壁面アイテム。",
  cardio: "ウォーキング、バイク、ローイングなど健康維持や減量向け。",
  "compact-gym": "ポケットジム、チューブ、折りたたみ器具など狭い部屋向け。",
  accessory: "腹筋ローラー、プッシュアップバー、収納ラックなど満足度を上げる周辺アイテム。",
};

const allRankingProducts = [
  {
    id: "irotec-multi-home-gym-dx",
    rank: 1,
    category: "multi-home-gym",
    name: "IROTEC マルチホームジムDX系",
    maker: "IROTEC",
    price: 55000,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=900&auto=format&fit=crop",
    rating: 4.2,
    summary: "5万円台で複数種目をまとめたい人に見られやすいマルチジム系。省スペースでも全身種目を作りやすい。",
    bestFor: "ラックを組むほどではないが、1台で全身を鍛えたい人",
    pros: ["種目数を増やしやすい", "価格が比較的現実的", "初心者がメニューを組みやすい"],
    cons: ["高重量の伸びしろは限定的", "搬入と組み立てスペースを確認したい"],
    productUrl: "https://www.amazon.co.jp/s?k=IROTEC+%E3%83%9E%E3%83%AB%E3%83%81%E3%83%9B%E3%83%BC%E3%83%A0%E3%82%B8%E3%83%A0",
    affiliateUrl: "https://www.amazon.co.jp/s?k=IROTEC+%E3%83%9E%E3%83%AB%E3%83%81%E3%83%9B%E3%83%BC%E3%83%A0%E3%82%B8%E3%83%A0&tag=myhomegym-22",
    isAffiliate: true,
  },
  {
    id: "bodymaker-home-gym-dx",
    rank: 2,
    category: "multi-home-gym",
    name: "BODYMAKER ホームジムDX系",
    maker: "BODYMAKER",
    price: 59000,
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=900&auto=format&fit=crop",
    rating: 4.1,
    summary: "1畳前後の設置をうたうマルチジム系。ラットプルやチェスト系を家でまとめたい人の候補。",
    bestFor: "限られた床面積でマシントレーニングをしたい人",
    pros: ["種目の幅が広い", "ブランド認知がある", "ラックより心理的に始めやすい"],
    cons: ["可動域や体格との相性確認が必要", "引っ越しや処分の手間は大きい"],
    productUrl: "https://www.amazon.co.jp/s?k=BODYMAKER+%E3%83%9B%E3%83%BC%E3%83%A0%E3%82%B8%E3%83%A0DX",
    isAffiliate: false,
  },
  {
    id: "wasai-mk780-half-rack",
    rank: 1,
    overallRank: 1,
    category: "power-rack",
    name: "WASAI ハーフラック パワーケージ MK780",
    maker: "WASAI",
    price: 25990,
    image: "https://m.media-amazon.com/images/I/51y1kpy4xEL._AC_SY300_SX300_QL70_ML2_.jpg",
    rating: 4.4,
    summary: "2万円台でベンチプレス、懸垂、スクワット、ベントオーバーローまで最低限の全身トレーニングを組める高コスパなハーフラック。",
    bestFor: "安く、省スペースに、最初の本格ホームジムを作りたい人",
    pros: ["とにかく安い", "ベンチプレス・懸垂・スクワットに対応", "ハーフラックなので省スペース", "ディップスやロー系の種目も組みやすい"],
    cons: ["バーベルとベンチは別売り", "高さ209cm/220cmなので天井高を確認したい", "本体耐荷重150kgの範囲で使う必要がある"],
    productUrl: "https://www.amazon.co.jp/WASAI-%E7%AD%8B%E5%8A%9B%E3%83%88%E3%83%AC%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0-%E3%83%91%E3%83%AF%E3%83%BC%E3%82%B1%E3%83%BC%E3%82%B8-%E3%83%99%E3%83%B3%E3%83%81%E3%83%97%E3%83%AC%E3%82%B9-MK780-%E6%9C%AC%E4%BD%93/dp/B0833K5KCM",
    affiliateUrl: "https://amzn.to/4uDapmU",
    isAffiliate: true,
  },
  {
    id: "barwing-hhr01-half-rack",
    rank: 2,
    category: "power-rack",
    name: "BARWING ハーフラック パワーラック BW-HHR01",
    maker: "BARWING",
    price: 21800,
    image: "https://m.media-amazon.com/images/I/61hRIKy-PSL._AC_SL1454_.jpg",
    rating: 4.2,
    summary: "横幅調整と48段階の高さ調整に対応したBARWINGのハーフラック。2万円前後でベンチプレス、スクワット、懸垂までまとめたい人に選びやすいコスパ枠。",
    bestFor: "できるだけ安く、幅調整できるハーフラックでBIG3と懸垂を始めたい人",
    pros: ["2万円前後で導入しやすい", "横幅調整で複数のシャフトに合わせやすい", "48段階の高さ調整が細かい", "懸垂バーやプレートラックも付く"],
    cons: ["組み立てや部品精度のレビューは確認したい", "高重量を本格的に伸ばすなら上位ラックも検討", "チンニングの高さや幅が体格に合うか確認したい"],
    productUrl: "https://amzn.to/4u9XY2o",
    affiliateUrl: "https://amzn.to/4u9XY2o",
    isAffiliate: true,
  },
  {
    id: "irotec-multi-power-rack",
    rank: 3,
    category: "power-rack",
    name: "IROTEC マルチパワーラック パワーゲージ",
    maker: "IROTEC",
    price: 72600,
    image: "https://m.media-amazon.com/images/I/61ma1locC+L._AC_SL1500_.jpg",
    rating: 4.5,
    summary: "ラットプル、ローイング、チンニング、ディップスまでまとめた本格寄りのパワーゲージ。W116×D145×H219cm、重量82kgで、ラック中心のホームジムをしっかり作りたい人向け。",
    bestFor: "ベンチプレス・スクワットに加えてラットプルやローイングも自宅で行いたい人",
    pros: ["ラットプルやローイングまで対応", "チンニングバーとディップスバー付き", "パワーゲージ型で安心感がある", "IROTECで器具を揃えやすい"],
    cons: ["価格と設置スペースは大きめ", "重量82kgで搬入と組み立ては大人2人推奨", "プレートとバーベルシャフトは別売り"],
    productUrl: "https://amzn.to/4nnsinB",
    affiliateUrl: "https://amzn.to/4nnsinB",
    isAffiliate: true,
  },
  {
    id: "steady-pull-up",
    rank: 1,
    category: "pull-up-stand",
    name: "STEADY 懸垂マシン系",
    maker: "STEADY",
    price: 16990,
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=900&auto=format&fit=crop",
    rating: 4.3,
    summary: "レビュー数が多く、懸垂マシンの代表候補。背中、腕、ディップスを低予算で始めやすい。",
    bestFor: "1万円台で上半身トレーニング環境を作りたい人",
    pros: ["レビュー量が多い", "高さ調整しやすい", "ラックより導入しやすい"],
    cons: ["設置時の揺れは床と体重で変わる", "部屋の高さ確認が必要"],
    productUrl: "https://www.amazon.co.jp/s?k=STEADY+%E6%87%B8%E5%9E%82%E3%83%9E%E3%82%B7%E3%83%B3",
    affiliateUrl: "https://www.amazon.co.jp/s?k=STEADY+%E6%87%B8%E5%9E%82%E3%83%9E%E3%82%B7%E3%83%B3&tag=myhomegym-22",
    isAffiliate: true,
  },
  {
    id: "pykes-peak-pull-up",
    rank: 2,
    category: "pull-up-stand",
    name: "PYKES PEAK ぶら下がり健康器系",
    maker: "PYKES PEAK",
    price: 8979,
    image: "https://images.unsplash.com/photo-1591291621164-2c6367723315?q=80&w=900&auto=format&fit=crop",
    rating: 4.1,
    summary: "1万円以下でも候補に入りやすい懸垂スタンド系。省コストで背中トレを追加したい人向け。",
    bestFor: "低予算で懸垂環境を作りたい人",
    pros: ["価格が安い", "レビューが多い", "導入のハードルが低い"],
    cons: ["耐荷重と安定感をレビューで確認", "ディップス用途は幅も見たい"],
    productUrl: "https://www.amazon.co.jp/s?k=PYKES+PEAK+%E6%87%B8%E5%9E%82%E3%83%9E%E3%82%B7%E3%83%B3",
    isAffiliate: false,
  },
  {
    id: "cuteefox-dumbbell-bench",
    rank: 2,
    category: "adjustable-dumbbell",
    name: "可変式ダンベル24kg + ベンチセット系",
    maker: "CuteeFox / GOGOJUMP系",
    price: 16999,
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=900&auto=format&fit=crop",
    rating: 4.1,
    summary: "2万円前後でダンベルとベンチを一気に揃えられるセット系。省スペースホームジムの入口として人気。",
    bestFor: "最初に一式そろえて全身トレーニングを始めたい人",
    pros: ["コスパが高い", "ベンチと同時に揃う", "種目数を増やしやすい"],
    cons: ["送料や耐久性の確認が必要", "高重量化には限界がある"],
    productUrl: "https://www.amazon.co.jp/s?k=%E5%8F%AF%E5%A4%89%E5%BC%8F%E3%83%80%E3%83%B3%E3%83%99%E3%83%AB+24kg+%E3%83%99%E3%83%B3%E3%83%81",
    affiliateUrl: "https://www.amazon.co.jp/s?k=%E5%8F%AF%E5%A4%89%E5%BC%8F%E3%83%80%E3%83%B3%E3%83%99%E3%83%AB+24kg+%E3%83%99%E3%83%B3%E3%83%81&tag=myhomegym-22",
    isAffiliate: true,
  },
  {
    id: "lysin-helixmirror-40kg",
    rank: 1,
    overallRank: 2,
    category: "adjustable-dumbbell",
    name: "ライシン ヘリックスミラー 40kg 2個セット",
    maker: "Lysin",
    price: 84800,
    image: "https://m.media-amazon.com/images/I/71HLS4+pWKL._AC_SL1500_.jpg",
    rating: 4.4,
    summary: "3kgから40kgまで1kg刻みで調整できるメタル仕様の可変式ダンベル。重量を細かく伸ばせて、膝に置いたときの痛さも出にくく、見た目のかっこよさも強い上位候補。",
    bestFor: "ダンベル種目を長く伸ばしたい人、見た目にもこだわりたい人",
    pros: ["1kg刻みで細かく重量調整できる", "40kgまで対応して伸びしろが大きい", "膝に置いても痛くなりにくい形状", "メタル感があり見た目がかっこいい"],
    cons: ["価格は高め", "1個42.5kg相当なので搬入と設置場所に注意", "プレートの向きや扱いは丁寧に確認したい"],
    productUrl: "https://www.amazon.co.jp/%E3%83%A9%E3%82%A4%E3%82%B7%E3%83%B3-%E3%83%98%E3%83%AA%E3%83%83%E3%82%AF%E3%82%B9%E3%83%9F%E3%83%A9%E3%83%BC-1kg%E5%88%BB%E3%81%BF-2%E5%80%8B%E3%82%BB%E3%83%83%E3%83%88-%E3%83%A1%E3%82%BF%E3%83%AB%E3%83%80%E3%83%B3%E3%83%99%E3%83%AB/dp/B0DTH36WT5",
    affiliateUrl: "https://amzn.to/3QYDL0G",
    isAffiliate: true,
  },
  {
    id: "flexbell-20kg-2kg-pair",
    rank: 2,
    category: "adjustable-dumbbell",
    name: "フレックスベル 正規品 可変式ダンベル 20kg 2kg刻み 2個セット",
    maker: "FLEXBELL",
    price: 56800,
    image: "https://m.media-amazon.com/images/I/71MFqxB+6XL._AC_SL1500_.jpg",
    rating: 4.7,
    summary: "2kgから20kgまで2kg刻みで10段階調整できる正規品の可変式ダンベル2個セット。片手で重量変更しやすく、見た目もスマートでホームジムに置きやすい。",
    bestFor: "20kgまでで十分な人、見た目と操作性を重視して省スペースにダンベルを置きたい人",
    pros: ["2kg刻みで扱いやすい", "片手で重量変更しやすい", "デザインがスマートで部屋になじみやすい", "レビュー評価が高い"],
    cons: ["20kgモデルは高重量狙いだと物足りない場合がある", "1kg刻みではない", "価格は安くない"],
    productUrl: "https://amzn.to/4d3s5Cw",
    affiliateUrl: "https://amzn.to/4d3s5Cw",
    isAffiliate: true,
  },
  {
    id: "barwing-adjustable-dumbbell-24kg-pair",
    rank: 3,
    category: "adjustable-dumbbell",
    name: "BARWING NEWモデル 可変式ダンベル 24kg 2個セット",
    maker: "BARWING",
    price: 19500,
    image: "https://m.media-amazon.com/images/I/61KhZ935u6L._AC_SL1500_.jpg",
    rating: 4.3,
    summary: "24kg×2個で2万円前後のかなり安い可変式ダンベル。2.5kgから24kgまで15段階で調整でき、まず自宅トレを始めたい人に選びやすいコスパ枠。",
    bestFor: "できるだけ安く可変式ダンベル2個セットを揃えたい人、初心者から中級者の自宅トレ用",
    pros: ["24kg×2個でかなり安い", "15段階調整で種目に合わせやすい", "購入数が多い人気商品", "ベース収納で省スペース"],
    cons: ["高級機より質感や操作感は比較したい", "24kg以上を狙う人は40kgモデルや上位機も検討", "ダイヤルのロック確認は毎回したい"],
    productUrl: "https://amzn.to/4wm6HzR",
    affiliateUrl: "https://amzn.to/4wm6HzR",
    isAffiliate: true,
  },
  {
    id: "gogojump-folding-training-bench",
    rank: 2,
    category: "bench",
    name: "GOGOJUMP トレーニングベンチ 折りたたみ式",
    maker: "GOGOJUMP",
    price: 5880,
    image: "https://m.media-amazon.com/images/I/71PKIE6omaL._AC_SL1500_.jpg",
    rating: 4.7,
    summary: "5千円台で買いやすい折りたたみ式の可変ベンチ。背もたれ7段階、座面4段階、レッグカール2段階に調整でき、組み立ての手軽さと収納性を重視する人に向く。",
    bestFor: "安くてレビュー数の多いベンチを、まず自宅トレ用に置きたい人",
    pros: ["価格が安い", "レビュー数と評価が強い", "折りたたんで収納しやすい", "背もたれ・座面・レッグ側を調整できる"],
    cons: ["耐荷重227kgなので高重量特化ではない", "本格ジム用ベンチほどの重量感はない", "幅32cmなので体格との相性を確認したい"],
    productUrl: "https://amzn.to/4ddctLo",
    affiliateUrl: "https://amzn.to/4ddctLo",
    isAffiliate: true,
  },
  {
    id: "barwing-dc04-training-bench",
    rank: 3,
    category: "bench",
    name: "BARWING トレーニングベンチ BW-DC04",
    maker: "BARWING",
    price: 14800,
    image: "https://m.media-amazon.com/images/I/71Ur64vwYfL._AC_SL1500_.jpg",
    rating: 4.4,
    summary: "インクライン、フラット、デクラインに対応するBARWINGの中位ベンチ。耐荷重300kg、5本パイプ方式、全面接地の極太角パイプで、安さだけでなく安定感も重視したい人向け。",
    bestFor: "格安ベンチより安定感を重視しつつ、折りたたみ収納もしたい人",
    pros: ["耐荷重300kgで安心感がある", "インクライン・フラット・デクラインに対応", "5本パイプ方式でフラット時も支えやすい", "ローラー付きで移動しやすい"],
    cons: ["1万円台なので最安重視なら2位のGOGOJUMPも候補", "重量15.8kgで軽量ベンチより移動は重め", "フラット時の形状や角度調整の好みは確認したい"],
    productUrl: "https://amzn.to/3R1CPsn",
    affiliateUrl: "https://amzn.to/3R1CPsn",
    isAffiliate: true,
  },
  {
    id: "barwing-bw-ajb06-bench",
    rank: 1,
    overallRank: 3,
    category: "bench",
    name: "BARWING 可変式トレーニングベンチ BW-AJB06",
    maker: "BARWING",
    price: 5780,
    image: "https://m.media-amazon.com/images/I/61947D6e1QL._AC_SL1500_.jpg",
    rating: 4.3,
    summary: "5千円台でインクライン、デクライン、フラットに対応する4WAYベンチ。角度調整が細かく、折りたたみ収納もしやすいので、最初のベンチとして選びやすい。",
    bestFor: "できるだけ安く、種目数を増やせるベンチを置きたい人",
    pros: ["価格がかなり安い", "4WAYで種目の幅を増やしやすい", "折りたたみ収納できる", "耐荷重500kg表記で安心感がある"],
    cons: ["本格ジム用ベンチほどの重量感はない", "高重量ダンベルを扱う人は安定感を確認したい", "保証期間は長期ではない"],
    productUrl: "https://www.amazon.co.jp/BARWING-%E3%83%90%E3%83%BC%E3%82%A6%E3%82%A3%E3%83%B3%E3%82%B0-%E3%83%88%E3%83%AC%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0%E3%83%99%E3%83%B3%E3%83%81-%E3%82%A4%E3%83%B3%E3%82%AF%E3%83%A9%E3%82%A4%E3%83%B3%E3%83%99%E3%83%B3%E3%83%81-%E3%83%87%E3%82%AF%E3%83%A9%E3%82%A4%E3%83%B3%E3%83%99%E3%83%B3%E3%83%81/dp/B0CTBY5221",
    affiliateUrl: "https://amzn.to/4tsU3fP",
    isAffiliate: true,
  },
  {
    id: "airhop-joint-mat",
    rank: 1,
    category: "floor-mat",
    name: "AIRHOP 24枚 8.92m² ジョイントマット",
    maker: "AIRHOP",
    price: 14999,
    image: "https://m.media-amazon.com/images/I/71zQ+bDShsL._AC_SL1500_.jpg",
    rating: 4.4,
    summary: "24枚で約8.92m²を敷けるEVAジョイントマット。1.2cm厚で床保護、防音、衝撃吸収をまとめて始めやすいホームジム用マット。",
    bestFor: "ラックやダンベルを置く前に、床の傷・音・衝撃対策をまとめて整えたい人",
    pros: ["24枚で広めに敷ける", "1.2cm厚で床保護と衝撃吸収に使いやすい", "部屋に合わせてカット・レイアウトしやすい", "掃除しやすいEVA素材"],
    cons: ["本格的な高重量ラック下ではゴムマットも検討したい", "設置直後はにおい対策として換気したい", "動きの大きい種目ではジョイント部のズレを確認したい"],
    productUrl: "https://amzn.to/4tuL4uC",
    affiliateUrl: "https://amzn.to/4tuL4uC",
    isAffiliate: true,
  },
  {
    id: "kawashima-structural-plywood-12mm",
    rank: 2,
    category: "floor-mat",
    name: "川島材木店 針葉樹合板 厚12mm 1820×910mm",
    maker: "川島材木店",
    price: 3700,
    image: "https://m.media-amazon.com/images/I/515iK4H9aqL._AC_SL1000_.jpg",
    rating: 4.5,
    summary: "3層構造で床を作るときの中層に使いやすい12mm針葉樹合板。ラックやベンチ下の荷重分散、床補強の下地材として検討しやすい。",
    bestFor: "マットだけでは不安で、ラックや高重量器具の下に荷重分散用の中層を入れたい人",
    pros: ["約1畳サイズでレイアウトを考えやすい", "12mm厚で床補強の中層に使いやすい", "構造用合板で強度を確保しやすい", "マットやゴム材と重ねて3層構造を作れる"],
    cons: ["表面は仕上げ材ではないのでバリや凹凸に注意", "大型商品なので送料と搬入経路を確認したい", "必要に応じてカットや面取りを検討したい"],
    productUrl: "https://amzn.to/3Rd2Zs8",
    affiliateUrl: "https://amzn.to/3Rd2Zs8",
    isAffiliate: true,
  },
  {
    id: "showa-eva-joint-mat-12mm",
    rank: 3,
    category: "floor-mat",
    name: "昭和化学 ジョイントマット EVA 30 8枚入り",
    maker: "昭和化学",
    price: 1510,
    image: "https://m.media-amazon.com/images/I/81YZtpcbCzL._AC_SL1450_.jpg",
    rating: 3.5,
    summary: "30×30cm、1.2cm厚のEVAジョイントマット。3層構造にする場合の一番下に敷いて面全体をカバーしやすく、最低限の床保護にも使える。",
    bestFor: "まず安く床全体をカバーしたい人、3層構造の下層としてEVAマットを敷きたい人",
    pros: ["価格を抑えて始めやすい", "30cm角で細かく敷き詰めやすい", "EVA素材でカットしやすい", "最低限の床傷・底冷え対策として使いやすい"],
    cons: ["本格的な防振目的では上層にゴムマットなどを重ねたい", "高重量ラック直下は合板や厚手マットとの併用を検討したい", "小判なので広い面積では枚数計算が必要"],
    productUrl: "https://amzn.to/42Y3XuS",
    affiliateUrl: "https://amzn.to/42Y3XuS",
    isAffiliate: true,
  },
  {
    id: "heavy-gym-mat",
    rank: 4,
    category: "floor-mat",
    name: "厚手ジムマット 20mm以上系",
    maker: "各社",
    price: 11680,
    image: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=900&auto=format&fit=crop",
    rating: 4.6,
    summary: "ラックや高重量ダンベルを置くなら厚手マットを検討。床保護と防振の安心感が上がる。",
    bestFor: "ラックや高重量ダンベルを置く人",
    pros: ["防振性を高めやすい", "床傷対策に強い", "見た目もジムらしくなる"],
    cons: ["費用が上がる", "段差やゴム臭を確認したい"],
    productUrl: "https://www.amazon.co.jp/s?k=%E5%8E%9A%E6%89%8B+%E3%82%B8%E3%83%A0%E3%83%9E%E3%83%83%E3%83%88+%E9%98%B2%E9%9F%B3",
    isAffiliate: false,
  },
  {
    id: "walkingpad-s1",
    rank: 1,
    category: "cardio",
    name: "WalkingPad S1 / Z系",
    maker: "KINGSMITH",
    price: 86800,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=900&auto=format&fit=crop",
    rating: 4.2,
    summary: "折りたたみ式ウォーキングマシンとして検索されやすいブランド。省スペースで有酸素習慣を作りやすい。",
    bestFor: "在宅勤務中や雨の日も歩きたい人",
    pros: ["折りたたみやすい", "室内で歩ける", "ブランド認知が高い"],
    cons: ["価格は高め", "走行音と床振動の確認が必要"],
    productUrl: "https://www.amazon.co.jp/s?k=WalkingPad+S1",
    affiliateUrl: "https://www.amazon.co.jp/s?k=WalkingPad+S1&tag=myhomegym-22",
    isAffiliate: true,
  },
  {
    id: "steady-spin-bike",
    rank: 2,
    category: "cardio",
    name: "STEADY スピンバイク系",
    maker: "STEADY",
    price: 49990,
    image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?q=80&w=900&auto=format&fit=crop",
    rating: 4.0,
    summary: "静音バイク系の定番候補。動画やアプリと合わせて継続したい人に向く。",
    bestFor: "静かに有酸素運動を続けたい人",
    pros: ["天候に左右されない", "運動強度を調整しやすい", "ながら運動しやすい"],
    cons: ["設置場所が固定される", "サドル相性を確認したい"],
    productUrl: "https://www.amazon.co.jp/s?k=STEADY+%E3%82%B9%E3%83%94%E3%83%B3%E3%83%90%E3%82%A4%E3%82%AF",
    isAffiliate: false,
  },
  {
    id: "unitree-pump-pro",
    rank: 1,
    category: "compact-gym",
    name: "Unitree PUMP Pro系",
    maker: "Unitree",
    price: 29800,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=900&auto=format&fit=crop",
    rating: 3.9,
    summary: "スマートポケットジムとして広告露出が目立つ省スペース器具。アプリ連携や電動負荷に惹かれる人向け。",
    bestFor: "ワンルームでケーブル系トレーニングを試したい人",
    pros: ["非常に省スペース", "アプリ連携がある", "持ち運びやすい"],
    cons: ["本格ウェイトとは刺激が違う", "耐久性レビューを確認したい"],
    productUrl: "https://www.amazon.co.jp/s?k=Unitree+PUMP+Pro",
    affiliateUrl: "https://www.amazon.co.jp/s?k=Unitree+PUMP+Pro&tag=myhomegym-22",
    isAffiliate: true,
  },
  {
    id: "vrtx-band",
    rank: 2,
    category: "compact-gym",
    name: "VRTX トレーニングチューブ系",
    maker: "VRTX",
    price: 4990,
    image: "https://images.unsplash.com/photo-1591291621164-2c6367723315?q=80&w=900&auto=format&fit=crop",
    rating: 4.4,
    summary: "チューブ系では素材や強度別展開が目立つ候補。省スペースでウォームアップや補助種目に使いやすい。",
    bestFor: "低予算で宅トレと補助種目を増やしたい人",
    pros: ["収納に困らない", "強度を選べる", "肩や背中の補助に便利"],
    cons: ["主役器具にはなりにくい", "劣化チェックが必要"],
    productUrl: "https://www.amazon.co.jp/s?k=VRTX+%E3%83%88%E3%83%AC%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0%E3%83%81%E3%83%A5%E3%83%BC%E3%83%96",
    isAffiliate: false,
  },
  {
    id: "ab-roller",
    rank: 1,
    category: "accessory",
    name: "腹筋ローラー系",
    maker: "各社",
    price: 1490,
    image: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=900&auto=format&fit=crop",
    rating: 4.4,
    summary: "非常に低価格で追加しやすく、検索・購入数が伸びやすい小物。省スペース投稿との相性がいい。",
    bestFor: "まず小物から家トレを始めたい人",
    pros: ["安い", "場所を取らない", "体幹トレに使いやすい"],
    cons: ["初心者はフォームに注意", "床保護マットもあると安心"],
    productUrl: "https://www.amazon.co.jp/s?k=%E8%85%B9%E7%AD%8B%E3%83%AD%E3%83%BC%E3%83%A9%E3%83%BC",
    affiliateUrl: "https://www.amazon.co.jp/s?k=%E8%85%B9%E7%AD%8B%E3%83%AD%E3%83%BC%E3%83%A9%E3%83%BC&tag=myhomegym-22",
    isAffiliate: true,
  },
  {
    id: "home-gym-storage-rack",
    rank: 2,
    category: "accessory",
    name: "ホームジム収納ラック系",
    maker: "各社",
    price: 5980,
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=900&auto=format&fit=crop",
    rating: 4.5,
    summary: "ダンベル、チューブ、ヨガマットをまとめる収納系。投稿写真の見た目改善にも効く。",
    bestFor: "器具が増えて部屋が散らかり始めた人",
    pros: ["見た目が整う", "器具を探しやすい", "キャスター付きなら掃除しやすい"],
    cons: ["耐荷重を確認したい", "ラック自体の設置幅が必要"],
    productUrl: "https://www.amazon.co.jp/s?k=%E3%83%9B%E3%83%BC%E3%83%A0%E3%82%B8%E3%83%A0+%E5%8F%8E%E7%B4%8D%E3%83%A9%E3%83%83%E3%82%AF",
    isAffiliate: false,
  },
] satisfies RankingProduct[];

export const rankingProducts = allRankingProducts.filter((product) =>
  [
    "wasai-mk780-half-rack",
    "barwing-hhr01-half-rack",
    "irotec-multi-power-rack",
    "lysin-helixmirror-40kg",
    "flexbell-20kg-2kg-pair",
    "barwing-adjustable-dumbbell-24kg-pair",
    "barwing-bw-ajb06-bench",
    "gogojump-folding-training-bench",
    "barwing-dc04-training-bench",
    "airhop-joint-mat",
    "kawashima-structural-plywood-12mm",
    "showa-eva-joint-mat-12mm",
  ].includes(product.id),
);

export function getRankingCategories() {
  return Object.keys(productCategoryLabels) as ProductCategory[];
}

export function getRankingProducts(category?: ProductCategory) {
  return rankingProducts
    .filter((product) => !category || product.category === category)
    .sort((a, b) => {
      if (category) {
        return a.rank - b.rank;
      }

      const aOverall = a.overallRank ?? Number.MAX_SAFE_INTEGER;
      const bOverall = b.overallRank ?? Number.MAX_SAFE_INTEGER;

      return aOverall - bOverall || a.category.localeCompare(b.category) || a.rank - b.rank;
    });
}
